resources:
  repositories:
  - repository: self
    checkoutOptions:
      submodules: true

pool:
  vmImage: windows-2019

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    version: '3.1.100'

- script: |
    dotnet restore
    dotnet build --output $(Build.ArtifactStagingDirectory)
  displayName: Build

- script: |
    dotnet pack --output $(Build.ArtifactStagingDirectory) -c Release /p:Version=1.0.$(Build.BuildId)
    dotnet nuget push $(Build.ArtifactStagingDirectory)\AutoFinance.Broker.1.0.$(Build.BuildId).nupkg --source https://www.nuget.org --api-key $(BrokerNugetApiKey)
    dotnet nuget push $(Build.ArtifactStagingDirectory)\InteractiveBrokers.TwsClient.1.0.$(Build.BuildId).nupkg --source https://www.nuget.org --api-key $(TwsClientNugetApiKey)
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: Push nuget
